# .github/labeler.yml
documentation:
  - changed-files:
      - any-glob-to-any-file: "**/*.md"

source-code:
  - changed-files:
      - any-glob-to-any-file: "**/*.go"

ci-cd:
  - changed-files:
      - any-glob-to-any-file: ".github/**"
