# winpath/.golangci.yml
run:
  build-tags:
    - windows
  tests: true
  timeout: 5m

linters:
  enable:
    - misspell
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - typecheck
    - unused

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    disable:
      - fieldalignment
    enable-all: true
  misspell:
    locale: US

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - govet
    - path: main\.go
      text: "fmt.Print"
    - path: registry\.go
      linters:
        - govet
  exclude-dirs:
    - third_party
    - builtin
    - examples
