# codecov.yml
coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        # Require 50% coverage minimum
        target: 50%
        threshold: 5%
    patch:
      default:
        # New code should have 60% coverage
        target: 60%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

ignore:
  # Ignore test files from coverage calculation
  - "**/*_test.go"
  # Ignore generated files
  - "**/mock_*.go"
